ARG base
FROM ${base}

LABEL maintainer="@hainest"

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Chicago

RUN apt -qq install -y --no-install-recommends git valgrind

# git sometimes has issues with auth, so don't use SSL verification
RUN GIT_SSL_NO_VERIFY=1 git clone --depth 1 --branch master https://github.com/dyninst/testsuite testsuite/src

COPY builds/options/build.pl /
