# Build Dyninst using latest sources for dependencies

name: Deps from latest sources

on:
  schedule:
    - cron: '0 21 * * 0' # Every Sunday at 11PM

jobs:
  build:
    permissions:
      packages: read
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dyninst/amd64/external-tests/deps-from-latest-source:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    name: build
    steps:
      - name: build
        run: |
          cd /
          bash test.sh -n 2 -l /dev/stdout
